version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - PGPORT=${DB_PORT}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - todoappgo_db_data:/var/lib/postgresql/data
    networks:
      - todoappgoNetwork

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - RUN_AUTO_MIGRATION=${RUN_AUTO_MIGRATION}
      - PORT=${PORT}
    networks:
      - todoappgoNetwork

volumes:
  todoappgo_db_data:

networks:
  todoappgoNetwork:
    driver: bridge
